version: '3.8'
name: dockertut
services:
    nodeapp:
      image: dockertutapp
      container_name: samplewala
      environment: 
        - PORT=4000
        - MONGO_URI=mongodb://admin:password@mongodb
      ports: 
        - 4000:4000
      depends_on:
        - mongodb
      networks:
        - customnet
    
    mongodb:
      image: mongo
      container_name: dockertutDB
      ports: 
        - 27070:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
      networks:
        - customnet
networks:
  dockernetwork:
    driver: bridge


