version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27070:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      # - ./data:/data/db #host type of volume
      - dockerTut-data:/data/db 

  backend22:
    build: 
      context: ./myapp
      dockerfile: Dockerfile
    container_name: backend_app
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:password@mongodb
      PORT: 3000

  nextcont:
    build: 
      context: ./nextapp
      dockerfile: Dockerfile
    ports: 
      - 4000:3000
    environment: 
      - SERVER_URL= http://backend22:3000
    depends_on: 
      - backend22
    # volumes:
    #   - ./nextapp:/app #we directly mount it with the volume so we can dynamic changes without create image again 
    develop:
      watch:
        - path: ./nextapp/package.json
          action: rebuild
        - path: ./nextapp/package-lock.json
          action: rebuild 
        - path: ./nextapp
          target: /app
          action: sync 

volumes:
  dockerTut-data:
    driver: local